src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $corps_messge = null;

    #[ORM\ManyToOne(inversedBy: 'messages')]
    private ?Utilisateur $author = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCorpsMessge(): ?string
    {
        return $this->corps_messge;
    }

    public function setCorpsMessge(string $corps_messge): self
    {
        $this->corps_messge = $corps_messge;

        return $this;
    }

    public function getAuthor(): ?Utilisateur
    {
        return $this->author;
    }

    public function setAuthor(?Utilisateur $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeInterface $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }
}

src/Controller/ChatController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Form\MessageType;
use App\Repository\MessageRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ChatController extends AbstractController
{
    #[Route('/', name: 'app_chat')]

    public function index(MessageRepository $messageRepository, Request $request, EntityManagerInterface $entityManager): Response
    {

        $messges = $entityManager->getRepository(Message::class)->findAll();

        $newMessage = new Message();
        $form = $this->createForm(MessageType::class, $newMessage);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $date = new \DateTime();
            $user = $this->getUser();
            $data = $form->getData();
            $newMessage = new Message();
            $newMessage->setCorpsMessge($data->getCorpsmessge());
            $newMessage->setAuthor($user);
            $newMessage->setCreateAt($date);
            $entityManager->persist($newMessage);
            $entityManager->flush();
            return $this->redirectToRoute('app_chat');
        }

        return $this->render('chat/index.html.twig', [

            'form'=>$form->createView(),
            'messages'=>$messges

        ]);
    }

    #[Route('delete/message/{id}', name: 'app_delete_message')]

    public function DeleteMessage(EntityManagerInterface $entityManager, $id): Response
    {

        $messge = $entityManager->getRepository(Message::class)->findById($id);

        if ($messge && $messge[0]->getAuthor() == $this->getUser() ){
            $entityManager->remove($messge[0]);
            $entityManager->flush();

            $this->addFlash('notice','Message supprimé avec succès !');
            return $this->redirectToRoute('app_chat');
        }
        $this->addFlash('alert',"Vous n'avez pas le droit de supprimé ce message car vous n'êtes pas l'auteur !");
        return $this->redirectToRoute('app_chat');
    }


    #[Route('edit/message/{id}', name: 'app_edit_message')]

    public function EditMessage(EntityManagerInterface $entityManager, $id, Request $request): Response
    {
        $messges = $entityManager->getRepository(Message::class)->findAll();

        $messge = $entityManager->getRepository(Message::class)->find($id);

        if (!$messge || $messge->getAuthor() != $this->getUser() ){

            $this->addFlash('alert',"Vous ne pouvez pas editer ce message car vous n'êtes pas l'auteur");
            return $this->redirectToRoute('app_chat');
        }

        $form = $this->createForm(MessageType::class, $messge);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $data = $form->getData();
            $messge->setCorpsMessge($data->getCorpsmessge());
           $entityManager->flush();

            $this->addFlash('notice',"Votre message à été modifier avec success");
            return $this->redirectToRoute('app_chat');
        }


        return $this->render('chat/index.html.twig', [

            'form'=>$form->createView(),
            'messages'=>$messges

        ]);
    }




}

templates/chat/index.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Live chat</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset("assets/style.css") }}">

</head>
<body>

<div class="container-sm mt-4" >
    <div >

        <div class="card text-left">
    <div class="card-header" style="background-color: black">
        <h1 style="width: 100%; text-align: center; color: #FFFFFF">Live message by DWWM</h1>
        {% if is_granted('ROLE_USER') %}
            <div style="margin-left: 80%">
                <button type="button" class="btn btn-primary mb-1" style="font-size: 12px;" >
                    <a href="{{ path('app_logout') }}" style="color: #FFFFFF">Se deconnecter</a></button>
                <button type="button" class="btn btn-info mb-1" style=" font-size: 12px;" >
                    <a href="{{ path('app_edit_profil', {id:app.user.id}) }}" style="color: #FFFFFF">Edit profile</a></button>

            </div>
        {% else %}
                <button type="button" class="btn btn-primary " style="margin-left: 80%"  ><a href="{{ path('app_login') }}" style="color: #FFFFFF">Se connecter</a></button>
                <button type="button" class="btn btn-secondary"  ><a href="{{ path('app_inscription') }}" style="color: #FFFFFF">S'inscrire</a></button>

        {% endif %}

        {% if is_granted('ROLE_USER') %}
        <div class="me-2 position-relative d-flex justify-content-start align-items-end mt-n5">
            <img src="/profilpics/{{ app.user.profilpic }}" alt="avatar" height="90px" width="90px" class="avatar-xl rounded-circle border border-4 border-primary position-relative">
            <a href="{{ path('app_edit_profil', {id:app.user.id}) }}" class="position-absolute ml-4">
                <img src="{{ asset('images/checked-mark.svg')}}" alt="virifé" height="30px" width="30px">
            </a> <span style="font-size: 25px; color: #FFFFFF">@{{ app.user.pseudo }}</span>
        </div>
        {% endif %}
        {% for notification in app.flashes('notice') %}
            <div class="alert alert-info">{{ notification }}</div>
        {% endfor %}

        {% for notification in app.flashes('alert') %}
            <div class="alert alert-danger">{{ notification }}</div>
        {% endfor %}
    </div>

    <div class="card-body" id="overflowTest" style="background-color: #FFFFFF">
        {% for message in messages %}
            <h6 class="card-title ">{{message.getAuthor().pseudo }}</h6>
            <p class="card-text" style="background-color: #DDDDDD; border-radius: 20px; padding: 15px; margin: 0;">{{ message.corpsMessge }} </p>
            <div style="margin-left: 80%; font-size: 10px"> {{ message.createAt|date("H:i") }}</div>
            <p>
                <span style=" background-color: #5eb5e0; border: #999999; padding: 5px; border-radius: 5px"><a style="color: #FFFFFF" href="{{ path('app_edit_message', {id:message.id}) }}">Edit</a></span> | <span style=" background-color:#FF5733 ; border: #999999; padding: 5px; border-radius: 5px"><a style="color: #FFFFFF" href="{{ path('app_delete_message', {id:message.id}) }}">delete</a></span>
            </p>
        {% endfor %}
    </div>
</div>
</div>

    {% if is_granted('ROLE_USER') %}
        <div class="w-100">
            {{ form_start(form) }}
            <div class="mb-3 m-3">
                {{ form_row(form.corps_messge) }}
            </div>
            <div class="mb-3 m-3 ">
                {{ form_row(form.send) }}
            </div>
            {{ form_end(form) }}

        </div>
        {% else %}
        <div>
            <p style="text-align: center; color: #B0413E; font-size: 20px"  class="mt3">
                Veuillez vous connectez ou créér un compte si vous n'en avez pas encore !
            </p>
        </div>

    {% endif %}


</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>